#!/bin/bash

# Project Launchers Installation
# Sets up project management with colored borders and bash aliases
# Creates config files, integrates with .bashrc and Hyprland

set -e  # Exit on error

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "$SCRIPT_DIR/../lib/common.sh" ]]; then
    source "$SCRIPT_DIR/../lib/common.sh"
else
    # Fallback color codes
    GREEN='\033[0;32m'
    BLUE='\033[0;34m'
    YELLOW='\033[1;33m'
    RED='\033[0;31m'
    CYAN='\033[0;36m'
    NC='\033[0m'
fi

echo "========================================"
echo "Project Launchers Installation"
echo "========================================"
echo ""

# ============================================================================
# Configuration paths
# ============================================================================

CONFIG_DIR="$HOME/.config/jomarchy"
GENERATED_DIR="$HOME/.local/share/jomarchy/generated"
PROJECTS_CONFIG="$CONFIG_DIR/projects.conf"
GENERATED_BASH="$GENERATED_DIR/project-functions.bash"
GENERATED_HYPR="$GENERATED_DIR/project-rules.hypr"
BASHRC="$HOME/.bashrc"
HYPRLAND_CONF="$HOME/.config/hypr/hyprland.conf"

# Source line for .bashrc
BASHRC_SOURCE='# Jomarchy Project Launcher
if [[ -f "$HOME/.local/share/jomarchy/generated/project-functions.bash" ]]; then
    source "$HOME/.local/share/jomarchy/generated/project-functions.bash"
fi'

# Source line for hyprland.conf
HYPR_SOURCE='# Jomarchy project window rules
source = ~/.local/share/jomarchy/generated/project-rules.hypr'

# ============================================================================
# Step 1: Create directories
# ============================================================================

echo -e "${BLUE}→${NC} Creating configuration directories..."

mkdir -p "$CONFIG_DIR"
mkdir -p "$GENERATED_DIR"

echo -e "${GREEN}✓${NC} Created $CONFIG_DIR"
echo -e "${GREEN}✓${NC} Created $GENERATED_DIR"
echo ""

# ============================================================================
# Step 2: Create projects.conf if it doesn't exist
# ============================================================================

if [[ ! -f "$PROJECTS_CONFIG" ]]; then
    echo -e "${BLUE}→${NC} Creating projects.conf with example header..."

    cat > "$PROJECTS_CONFIG" << 'HEADER'
# Jomarchy Project Configuration
# Format: KEY|NAME|PATH|PORT|DB_ENV_VAR|ACTIVE_COLOR|INACTIVE_COLOR
#
# KEY: lowercase identifier (used for j<key> and cc<key> aliases)
# NAME: display name (used in window titles, e.g., "CHIMARO:")
# PATH: project path (~ will be expanded)
# PORT: dev server port (leave empty if no dev server)
# DB_ENV_VAR: environment variable for database URL (leave empty if none)
# ACTIVE_COLOR: hex color for active border (without #, e.g., 00d4aa)
# INACTIVE_COLOR: hex color for inactive border (without #, e.g., 00a080)
#
# Example:
# chimaro|CHIMARO|~/code/chimaro|3500|DATABASE_URL|00d4aa|00a080
# jomarchy|JOMARCHY|~/code/jomarchy|||ffdd00|ccaa00

HEADER

    echo -e "${GREEN}✓${NC} Created $PROJECTS_CONFIG with example header"
else
    echo -e "${YELLOW}⊘${NC} projects.conf already exists, keeping existing"
fi

# ============================================================================
# Step 3: Create empty generated files if they don't exist
# ============================================================================

if [[ ! -f "$GENERATED_BASH" ]]; then
    echo -e "${BLUE}→${NC} Creating empty project-functions.bash..."
    cat > "$GENERATED_BASH" << 'EMPTY'
#!/bin/bash
# AUTO-GENERATED by jomarchy project manager
# This file will be populated when you add projects
# Run: jomarchy --projects -> Regenerate All
EMPTY
    chmod +x "$GENERATED_BASH"
    echo -e "${GREEN}✓${NC} Created $GENERATED_BASH"
else
    echo -e "${YELLOW}⊘${NC} project-functions.bash already exists"
fi

if [[ ! -f "$GENERATED_HYPR" ]]; then
    echo -e "${BLUE}→${NC} Creating empty project-rules.hypr..."
    cat > "$GENERATED_HYPR" << 'EMPTY'
# AUTO-GENERATED by jomarchy project manager
# This file will be populated when you add projects
# Run: jomarchy --projects -> Regenerate All
EMPTY
    echo -e "${GREEN}✓${NC} Created $GENERATED_HYPR"
else
    echo -e "${YELLOW}⊘${NC} project-rules.hypr already exists"
fi

echo ""

# ============================================================================
# Step 4: Add source line to .bashrc (idempotent)
# ============================================================================

echo -e "${BLUE}→${NC} Configuring .bashrc..."

# Check if already added (look for the config file path)
if grep -q "project-functions.bash" "$BASHRC" 2>/dev/null; then
    echo -e "${YELLOW}⊘${NC} .bashrc already sources project-functions.bash"
else
    # Backup .bashrc
    cp "$BASHRC" "${BASHRC}.bak.$(date +%s)"
    echo -e "${CYAN}  Backed up .bashrc${NC}"

    # Append source line
    echo "" >> "$BASHRC"
    echo "$BASHRC_SOURCE" >> "$BASHRC"

    echo -e "${GREEN}✓${NC} Added source line to .bashrc"
fi

# ============================================================================
# Step 5: Add source line to hyprland.conf (idempotent)
# ============================================================================

echo -e "${BLUE}→${NC} Configuring hyprland.conf..."

if [[ ! -f "$HYPRLAND_CONF" ]]; then
    echo -e "${YELLOW}⚠${NC} hyprland.conf not found at $HYPRLAND_CONF"
    echo -e "${CYAN}  You'll need to add this line manually:${NC}"
    echo -e "${CYAN}  $HYPR_SOURCE${NC}"
else
    # Check if already added
    if grep -q "project-rules.hypr" "$HYPRLAND_CONF" 2>/dev/null; then
        echo -e "${YELLOW}⊘${NC} hyprland.conf already sources project-rules.hypr"
    else
        # Backup hyprland.conf
        cp "$HYPRLAND_CONF" "${HYPRLAND_CONF}.bak.$(date +%s)"
        echo -e "${CYAN}  Backed up hyprland.conf${NC}"

        # Append source line
        echo "" >> "$HYPRLAND_CONF"
        echo "$HYPR_SOURCE" >> "$HYPRLAND_CONF"

        echo -e "${GREEN}✓${NC} Added source line to hyprland.conf"
    fi
fi

echo ""

# ============================================================================
# Step 6: Check for project-manager-lib.sh and offer interactive setup
# ============================================================================

LIB_FILE="$SCRIPT_DIR/../lib/project-manager-lib.sh"

if [[ -f "$LIB_FILE" ]]; then
    # Source the library for functions
    source "$LIB_FILE"

    # Check if there are already projects configured
    project_count=$(count_projects 2>/dev/null || echo "0")

    if [[ "$project_count" -eq 0 ]]; then
        echo -e "${CYAN}No projects configured yet.${NC}"
        echo ""

        # Check if gum is available
        if command -v gum &>/dev/null; then
            # Ask user what they want to do
            echo -e "${BLUE}Would you like to set up projects now?${NC}"
            choice=$(echo -e "Scan ~/code for repositories\nImport from .bashrc\nSkip for now" | \
                gum choose --header="Choose setup method:")

            case "$choice" in
                "Scan ~/code for repositories")
                    # Check if ~/code exists and has repos
                    if [[ -d "$HOME/code" ]]; then
                        repos=$(scan_code_directory 2>/dev/null || echo "")
                        if [[ -n "$repos" ]]; then
                            echo -e "\n${CYAN}Found repositories in ~/code:${NC}"
                            echo "$repos" | cut -d'|' -f1 | while read -r name; do
                                echo -e "  • $name"
                            done
                            echo ""
                            echo -e "${YELLOW}Run 'jomarchy --projects' to add them interactively.${NC}"
                        else
                            echo -e "${YELLOW}No new repositories found in ~/code.${NC}"
                        fi
                    else
                        echo -e "${YELLOW}~/code directory doesn't exist.${NC}"
                    fi
                    ;;
                "Import from .bashrc")
                    # Check if old PROJECT_CONFIG exists
                    if grep -q "^declare -A PROJECT_CONFIG" "$BASHRC" 2>/dev/null; then
                        echo -e "${GREEN}Found PROJECT_CONFIG in .bashrc!${NC}"
                        echo -e "${YELLOW}Run 'jomarchy --projects' and select 'Import from .bashrc'.${NC}"
                    else
                        echo -e "${YELLOW}No PROJECT_CONFIG found in .bashrc.${NC}"
                    fi
                    ;;
                "Skip for now")
                    echo -e "${CYAN}Skipped. Run 'jomarchy --projects' later to set up projects.${NC}"
                    ;;
            esac
        else
            echo -e "${YELLOW}gum not installed - skipping interactive setup.${NC}"
            echo -e "${CYAN}Run 'jomarchy --projects' later to set up projects.${NC}"
        fi
    else
        echo -e "${GREEN}✓${NC} Found $project_count project(s) already configured"

        # Offer to regenerate
        if command -v gum &>/dev/null; then
            if gum confirm "Regenerate bash functions and Hyprland rules?"; then
                regenerate_all
            fi
        else
            echo -e "${CYAN}Run 'jomarchy --projects' -> 'Regenerate All' to update configs.${NC}"
        fi
    fi
else
    echo -e "${YELLOW}⚠${NC} project-manager-lib.sh not found"
    echo -e "${CYAN}Run 'jomarchy --projects' to manage projects after installation completes.${NC}"
fi

echo ""

# ============================================================================
# Step 7: Track profile installation
# ============================================================================

if declare -f add_installed_profile &>/dev/null; then
    add_installed_profile "PROJECT_LAUNCHERS"
    echo -e "${GREEN}✓${NC} Marked PROJECT_LAUNCHERS as installed"
else
    # Fallback if common.sh wasn't sourced
    PROFILES_FILE="$CONFIG_DIR/installed_profiles"
    if ! grep -q "^PROJECT_LAUNCHERS$" "$PROFILES_FILE" 2>/dev/null; then
        echo "PROJECT_LAUNCHERS" >> "$PROFILES_FILE"
        echo -e "${GREEN}✓${NC} Marked PROJECT_LAUNCHERS as installed"
    fi
fi

echo ""

# ============================================================================
# Summary
# ============================================================================

echo "========================================"
echo "Installation Complete"
echo "========================================"
echo ""
echo -e "${GREEN}✓${NC} Project launcher system installed"
echo ""
echo -e "${CYAN}Configuration files:${NC}"
echo -e "  • $PROJECTS_CONFIG"
echo -e "  • $GENERATED_BASH"
echo -e "  • $GENERATED_HYPR"
echo ""
echo -e "${CYAN}Next steps:${NC}"
echo -e "  1. Run 'jomarchy --projects' to add projects"
echo -e "  2. Use 'j<key>' to launch projects (e.g., 'jc' for chimaro)"
echo -e "  3. Use 'cc<key>' to launch Claude Code for a project"
echo ""
echo -e "${YELLOW}Note: Source your .bashrc or start a new terminal to use aliases.${NC}"
echo ""
